export const OLYMPIC_PENINSULA_VERIFIED_ON = "2026-08-21";
export const OLYMPIC_PENINSULA_REVIEW_DUE_ON = "2027-02-21";

export const olympicPeninsulaAreas = [
  {
    id: "olympic-port-townsend",
    slug: "port-townsend",
    name: "Port Townsend",
    kind: "town",
    latitude: 48.1181,
    longitude: -122.7604,
    summary: "A historic waterfront town and relaxed eastern gateway to the Olympic Peninsula, with enough walkability for a real first overnight.",
  },
  {
    id: "olympic-sequim-dungeness",
    slug: "sequim-dungeness",
    name: "Sequim & Dungeness",
    kind: "town",
    latitude: 48.0795,
    longitude: -123.1018,
    summary: "A north-peninsula base where wildlife, the Strait shoreline and an easy town rhythm can balance a larger Olympic trip.",
  },
  {
    id: "olympic-port-angeles",
    slug: "port-angeles-hurricane-ridge",
    name: "Port Angeles & Hurricane Ridge",
    kind: "town",
    latitude: 48.1181,
    longitude: -123.4307,
    summary: "A practical Strait-side base for downtown evenings and a separate mountain outing when Hurricane Ridge road conditions cooperate.",
  },
  {
    id: "olympic-lake-crescent",
    slug: "lake-crescent",
    name: "Lake Crescent",
    kind: "park",
    latitude: 48.0678,
    longitude: -123.8174,
    summary: "A deep glacial lake and lowland-forest pause west of Port Angeles, with short trails rather than a mandatory big hike.",
  },
  {
    id: "olympic-forks-hoh",
    slug: "forks-hoh-rain-forest",
    name: "Forks & Hoh Rain Forest",
    kind: "coastal_area",
    latitude: 47.9504,
    longitude: -124.3855,
    summary: "The west-side gateway to temperate rain forest, where an easy old-growth walk needs its own time rather than becoming a roadside detour.",
  },
  {
    id: "olympic-quinault",
    slug: "quinault-rain-forest",
    name: "Quinault Rain Forest",
    kind: "park",
    latitude: 47.4709,
    longitude: -123.8581,
    summary: "A southern Olympic rain-forest base with short interpretive trails and a much calmer final day than trying to add more coast driving.",
  },
] as const;

export const olympicPeninsulaStops = [
  {
    id: "port-townsend-historic-waterfront",
    slug: "port-townsend-historic-waterfront",
    name: "Port Townsend Historic Waterfront",
    kind: "historic_downtown",
    areaId: "olympic-port-townsend",
    latitude: 48.1171,
    longitude: -122.7591,
    typicalDurationMinutes: 120,
    indoorOutdoor: "mixed",
    childFit: "good",
    weatherSensitivity: "low",
    summary: "A flexible first-evening walk for waterfront history, food and a low-effort transition into the peninsula.",
    preferences: ["city", "historic", "ocean"],
  },
  {
    id: "fort-worden",
    slug: "fort-worden-historical-state-park",
    name: "Fort Worden Historical State Park",
    kind: "park",
    areaId: "olympic-port-townsend",
    latitude: 48.1344,
    longitude: -122.7669,
    typicalDurationMinutes: 180,
    indoorOutdoor: "mixed",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A broad historic fort-and-beach park where families can choose one battery, beach or museum element instead of trying to cover the whole campus.",
    preferences: ["historic", "ocean", "forest"],
  },
  {
    id: "olympic-game-farm",
    slug: "olympic-game-farm",
    name: "Olympic Game Farm",
    kind: "farm",
    areaId: "olympic-sequim-dungeness",
    latitude: 48.0948,
    longitude: -123.0639,
    typicalDurationMinutes: 150,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A self-guided drive-through wildlife stop that works as the one major family anchor for a Sequim day.",
    preferences: ["animals"],
  },
  {
    id: "dungeness-national-wildlife-refuge",
    slug: "dungeness-national-wildlife-refuge",
    name: "Dungeness National Wildlife Refuge",
    kind: "park",
    areaId: "olympic-sequim-dungeness",
    latitude: 48.1668,
    longitude: -123.1097,
    typicalDurationMinutes: 90,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "high",
    summary: "A shoreline-and-wildlife pause at the start of Dungeness Spit; treat the lighthouse walk as a separate, longer outing.",
    preferences: ["animals", "ocean", "forest"],
  },
  {
    id: "port-angeles-waterfront",
    slug: "port-angeles-waterfront-downtown",
    name: "Port Angeles Waterfront & Downtown",
    kind: "historic_downtown",
    areaId: "olympic-port-angeles",
    latitude: 48.1187,
    longitude: -123.4305,
    typicalDurationMinutes: 90,
    indoorOutdoor: "mixed",
    childFit: "good",
    weatherSensitivity: "low",
    summary: "A useful town-and-waterfront reset before or after a mountain day, without adding another long scenic drive.",
    preferences: ["city", "ocean", "historic"],
  },
  {
    id: "hurricane-ridge",
    slug: "hurricane-ridge",
    name: "Hurricane Ridge",
    kind: "viewpoint",
    areaId: "olympic-port-angeles",
    latitude: 47.9691,
    longitude: -123.4986,
    typicalDurationMinutes: 180,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "high",
    summary: "Olympic's accessible mountain viewpoint, but a separate half-day that depends on road, weather and parking conditions.",
    preferences: ["mountains", "forest"],
  },
  {
    id: "lake-crescent-shoreline",
    slug: "lake-crescent-shoreline",
    name: "Lake Crescent Shoreline",
    kind: "park",
    areaId: "olympic-lake-crescent",
    latitude: 48.0636,
    longitude: -123.7894,
    typicalDurationMinutes: 120,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A slower lake-and-forest stop for the days when a scenic drive and short shoreline time are enough.",
    preferences: ["lake", "forest", "mountains"],
  },
  {
    id: "marymere-falls",
    slug: "marymere-falls",
    name: "Marymere Falls",
    kind: "hike",
    areaId: "olympic-lake-crescent",
    latitude: 48.0587,
    longitude: -123.7897,
    typicalDurationMinutes: 150,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A family-suitable forest walk to a waterfall; conditions and bridge access should be checked before treating it as the day's anchor.",
    preferences: ["waterfall", "forest", "lake"],
  },
  {
    id: "hoh-hall-of-mosses",
    slug: "hall-of-mosses-trail",
    name: "Hall of Mosses Trail",
    kind: "hike",
    areaId: "olympic-forks-hoh",
    latitude: 47.8609,
    longitude: -123.9348,
    typicalDurationMinutes: 120,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "An easy old-growth rain-forest loop that earns a dedicated visit; summer access can require an early or late arrival.",
    preferences: ["forest", "waterfall"],
  },
  {
    id: "maple-glade-trail",
    slug: "maple-glade-trail",
    name: "Maple Glade Trail",
    kind: "hike",
    areaId: "olympic-quinault",
    latitude: 47.4727,
    longitude: -123.8594,
    typicalDurationMinutes: 60,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A short forest loop near the Quinault ranger station for seeing mossy rain forest without committing the final day to a long trail.",
    preferences: ["forest"],
  },
  {
    id: "kestner-homestead-trail",
    slug: "kestner-homestead-trail",
    name: "Kestner Homestead Trail",
    kind: "hike",
    areaId: "olympic-quinault",
    latitude: 47.4736,
    longitude: -123.86,
    typicalDurationMinutes: 90,
    indoorOutdoor: "outdoor",
    childFit: "good",
    weatherSensitivity: "medium",
    summary: "A short historic homestead-and-rain-forest loop that offers a gentler final anchor than another major scenic drive.",
    preferences: ["forest", "historic"],
  },
] as const;

export const olympicPeninsulaHikeDetails = [
  {
    stopId: "marymere-falls",
    difficulty: "easy",
    distanceMiles: 3.2,
    elevationGainFeet: 194,
    routeShape: "out_and_back",
    trailheadLatitude: 48.0587,
    trailheadLongitude: -123.7897,
  },
  {
    stopId: "hoh-hall-of-mosses",
    difficulty: "easy",
    distanceMiles: 0.8,
    elevationGainFeet: 100,
    routeShape: "loop",
    trailheadLatitude: 47.8609,
    trailheadLongitude: -123.9348,
  },
  {
    stopId: "maple-glade-trail",
    difficulty: "easy",
    distanceMiles: 0.5,
    elevationGainFeet: 0,
    routeShape: "loop",
    trailheadLatitude: 47.4727,
    trailheadLongitude: -123.8594,
  },
  {
    stopId: "kestner-homestead-trail",
    difficulty: "easy",
    distanceMiles: 1.3,
    elevationGainFeet: 0,
    routeShape: "loop",
    trailheadLatitude: 47.4736,
    trailheadLongitude: -123.86,
  },
] as const;

export const olympicPeninsulaSources = [
  { id: "enjoy-port-townsend", title: "Enjoy Port Townsend", url: "https://enjoypt.com/", publisherType: "visitor_bureau" },
  { id: "wa-parks-fort-worden", title: "Fort Worden Historical State Park", url: "https://parks.wa.gov/find-parks/state-parks/fort-worden-historical-state-park", publisherType: "government" },
  { id: "olympic-game-farm-source", title: "Olympic Game Farm", url: "https://olygamefarm.com/", publisherType: "official" },
  { id: "fws-dungeness", title: "Dungeness National Wildlife Refuge visitor information", url: "https://www.fws.gov/refuge/dungeness/visit-us", publisherType: "government" },
  { id: "visit-port-angeles", title: "Visit Port Angeles", url: "https://www.visitportangeles.com/", publisherType: "visitor_bureau" },
  { id: "nps-hurricane-ridge", title: "Visiting Hurricane Ridge", url: "https://www.nps.gov/olym/planyourvisit/visiting-hurricane-ridge.htm", publisherType: "government" },
  { id: "nps-lake-crescent", title: "Visiting Lake Crescent", url: "https://www.nps.gov/olym/planyourvisit/visiting-lake-crescent.htm", publisherType: "government" },
  { id: "nps-hoh", title: "Visiting the Hoh Rain Forest", url: "https://www.nps.gov/olym/planyourvisit/visiting-the-hoh.htm", publisherType: "government" },
  { id: "nps-quinault", title: "Visiting Quinault", url: "https://www.nps.gov/olym/planyourvisit/visiting-quinault.htm", publisherType: "government" },
  { id: "nps-olympic-getting-around", title: "Getting Around Olympic", url: "https://www.nps.gov/olym/planyourvisit/gettingaround.htm", publisherType: "government" },
  { id: "nps-olympic-trip-ideas", title: "Olympic National Park trip ideas", url: "https://www.nps.gov/olym/planyourvisit/tripideas.htm", publisherType: "government" },
] as const;

export const olympicPeninsulaRoute = {
  id: "olympic-peninsula-loop",
  slug: "olympic-peninsula-loop",
  name: "Olympic Peninsula Loop",
  shape: "loop",
  countryCode: "US",
  minDays: 2,
  maxDays: 4,
  summary: "A clockwise Olympic Peninsula corridor from Port Townsend through the north side, rain forest and Quinault. Nearbound presents realistic connected sections, not a promise to see every ecosystem in one rush.",
} as const;

export const olympicPeninsulaTripPlans = [
  {
    id: "olympic-north-shore",
    slug: "olympic-north-shore",
    name: "Olympic north shore",
    summary: "A deliberate Port Townsend-to-Lake Crescent trip with time for one wildlife or history anchor, one Port Angeles overnight and a slower lake day.",
    startAreaId: "olympic-port-townsend",
    endAreaId: "olympic-lake-crescent",
    minDays: 2,
    minDaysWithChildren: 3,
    maxDays: 3,
  },
  {
    id: "olympic-ecosystems-loop",
    slug: "olympic-ecosystems-loop",
    name: "Olympic ecosystems loop",
    summary: "A full north-to-west Olympic loop with a mountain or lake choice, one rain-forest anchor and a calm Quinault finish instead of a packed national-park checklist.",
    startAreaId: "olympic-port-angeles",
    endAreaId: "olympic-quinault",
    minDays: 3,
    minDaysWithChildren: 4,
    maxDays: 4,
  },
] as const;

export const olympicPeninsulaRouteLegs = [
  { position: 1, fromAreaId: "olympic-port-townsend", toAreaId: "olympic-sequim-dungeness", distanceMiles: 51, driveMinutes: 75 },
  { position: 2, fromAreaId: "olympic-sequim-dungeness", toAreaId: "olympic-port-angeles", distanceMiles: 18, driveMinutes: 30 },
  { position: 3, fromAreaId: "olympic-port-angeles", toAreaId: "olympic-lake-crescent", distanceMiles: 21, driveMinutes: 30 },
  { position: 4, fromAreaId: "olympic-lake-crescent", toAreaId: "olympic-forks-hoh", distanceMiles: 38, driveMinutes: 60 },
  { position: 5, fromAreaId: "olympic-forks-hoh", toAreaId: "olympic-quinault", distanceMiles: 69, driveMinutes: 105 },
] as const;

export function sourceForOlympicPeninsulaArea(areaId: string) {
  if (areaId === "olympic-port-townsend") return "enjoy-port-townsend";
  if (areaId === "olympic-sequim-dungeness") return "fws-dungeness";
  if (areaId === "olympic-port-angeles") return "visit-port-angeles";
  if (areaId === "olympic-lake-crescent") return "nps-lake-crescent";
  if (areaId === "olympic-forks-hoh") return "nps-hoh";
  return "nps-quinault";
}

export function sourceForOlympicPeninsulaStop(stopId: string) {
  if (stopId === "port-townsend-historic-waterfront") return "enjoy-port-townsend";
  if (stopId === "fort-worden") return "wa-parks-fort-worden";
  if (stopId === "olympic-game-farm") return "olympic-game-farm-source";
  if (stopId === "dungeness-national-wildlife-refuge") return "fws-dungeness";
  if (stopId === "port-angeles-waterfront") return "visit-port-angeles";
  if (stopId === "hurricane-ridge") return "nps-hurricane-ridge";
  if (["lake-crescent-shoreline", "marymere-falls"].includes(stopId)) return "nps-lake-crescent";
  if (stopId === "hoh-hall-of-mosses") return "nps-hoh";
  return "nps-quinault";
}
